### ISSUE TITLE
XX% OF XX does not seem to work

### ISSUE THREAD

**Issue by HiMynameisALL** [biati-digital/alfred-calculate-anything#154]
![CleanShot 2023-12-26 at 15 05 40@2x](https://github.com/biati-digital/alfred-calculate-anything/assets/154891448/b4b51768-9050-43ea-b92f-e6969a29eb55)

pretty much all other % functions do work but not this one for some reason at least for me.

![CleanShot 2023-12-26 at 15 06 38@2x](https://github.com/biati-digital/alfred-calculate-anything/assets/154891448/a31ad001-738c-4820-acb3-f2becfe2851f)

**Comment by T0rukMakt0** [comment]
same here. following

**Comment by biati-digital** [comment]
This should be fixed in the latest version, please try it and let me know if it's working.

**Comment by ddeboer** [comment]
Yes, working now! (Though [the gallery still shows version 4.0.5](https://alfred.app/workflows/biatidigital/calculate-anything/).)

**Comment by biati-digital** [comment]
> Yes, working now! (Though [the gallery still shows version 4.0.5](https://alfred.app/workflows/biatidigital/calculate-anything/).)

Thanks for letting me know it's working.

I've no control over the gallery page, the Alfred team added the workflow in the gallery and I guess it checks automatically for new releases on this repo from time to time. I'm sure we just need to wait some time and the gallery will show the latest version.
